---
title: "JobAttritionNaiveBayes"
author: "Derek Rogers"
date: "2022-11-23"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Loading Data From S3 URL Using RCurl
```{r}
library("RCurl") 
library(jsonlite)
library(ggplot2)
library(class)
library(caret)
library(e1071)
library(dplyr)
library(tidyverse)
library(aws.s3)
library(gtools)

creativity <- read.table(textConnection(getURL(
  "https://smuds6306.s3.us-east-2.amazonaws.com/Creativity.csv"
)), sep=",", header=TRUE)

iris3 <- jsonlite::fromJSON("https://smuds6306.s3.us-east-2.amazonaws.com/iris.json")

climate <- read.table(textConnection(getURL(
  "https://cgiardata.s3-us-west-2.amazonaws.com/ccafs/amzn.csv"
)), sep=",", header=TRUE)
```
           
```{r}
Sys.setenv("AWS_ACCESS_KEY_ID" = "AKIAVW4VHW4VPB7MHZWA",
           "AWS_SECRET_ACCESS_KEY" = "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",
           "AWS_DEFAULT_REGION" = "us-east-2")
```

```{r}
# Using aws.s3
aws.s3::bucketlist()
aws.s3::get_bucket("smuddsproject2")

#Read in Creativity.csv
turnoverDataframe = s3read_using(FUN = read.csv,
                    bucket = "smuddsproject2",
                    object = "CaseStudy2-data.csv")

testAttritionTurnoverDataframe = s3read_using(FUN = read.csv,
                    bucket = "smuddsproject2",
                    object = "CaseStudy2CompSet No Attrition.csv")

turnoverDataframe$Attrition = as.factor(turnoverDataframe$Attrition)
```

```{r}
# Remove columns with no unique values: Over18, EmployeeCount, StandardHours
# Remove employee number as it is only used as a unique identifier and not useful for attrition analysis
dropColumns = c("Over18", "StandardHours", "EmployeeCount", "EmployeeNumber")
turnoverDataframe = turnoverDataframe[ , !(names(turnoverDataframe) %in% dropColumns)]
```

```{r}
# Reorder so Attrition is the first column, ID is the second column, and Age is the 3rd column
# Only keep numeric columns
turnoverDataframe = turnoverDataframe[,c(3,1,2,5,7,8,10,12,13,14,16,18,19,20,22,23,24,25,26,27,28,29,30,31,32)]

apply(turnoverDataframe, 2, function(x) length(unique(x)))
ncol(turnoverDataframe)
```

```{r}
ncol(turnoverDataframe)
turnoverDataframe$LogMonthlyIncome = log(turnoverDataframe$MonthlyIncome)
turnoverDataframe
```

```{r}
trainingPercent = numberOfYesObservations / numberOfNoObservations

#Seperate the yes/no attrition observations into 2 dataframes
noAttritionTrainingDataframe = turnoverDataframe[turnoverDataframe$Attrition == 'No',]
yesAttritionTrainingDataframe = turnoverDataframe[turnoverDataframe$Attrition == 'Yes',]

trainingIndicies = sample(1:dim(noAttritionTrainingDataframe)[1], round(trainingPercent * dim(noAttritionTrainingDataframe)[1]))
trainingDataSet = rbind(noAttritionTrainingDataframe[trainingIndicies,], yesAttritionTrainingDataframe)

model = naiveBayes(trainingDataSet[, c(3, 5, 6)], trainingDataSet$Attrition, laplace = 1)
confusionMatrix(table(predict(model, turnoverDataframe[, c(3, 5, 6)]), turnoverDataframe$Attrition))
```

```{r}
trainingPercent = numberOfYesObservations / numberOfNoObservations

#Seperate the yes/no attrition observations into 2 dataframes
noAttritionTrainingDataframe = turnoverDataframe[turnoverDataframe$Attrition == 'No',]
yesAttritionTrainingDataframe = turnoverDataframe[turnoverDataframe$Attrition == 'Yes',]

iterations = 25

columnCombinations = c(3,4,5,6,7,8,9,10,11,13,14,15,16,17,18,19,20,21,22,23,24,25,26)
#columnCombinations = c(3,4,5,6)

for(i in 2:length(columnCombinations)){
  resultsDataframe = data.frame(accuracy = double(), specificity = double(), combination = character())
  columnCombinationsMatrix = combn(columnCombinations, i)
  for(j in 1:ncol(columnCombinationsMatrix)){
    iterationResultsDataframe = data.frame(accuracy = double(), specificity = double(), combination = character())
    for(l in 1:iterations){
      # TODO: figure out how to test on the full dataset instead of the trainingDataSet
      # https://stackoverflow.com/questions/66004740/how-to-apply-knn-model-on-the-test-dataset-after-cross-validation-in-r
      
      trainingIndicies = sample(1:dim(noAttritionTrainingDataframe)[1], round(trainingPercent * dim(noAttritionTrainingDataframe)[1]))
      trainingDataSet = rbind(noAttritionTrainingDataframe[trainingIndicies,], yesAttritionTrainingDataframe)
      
      model = naiveBayes(trainingDataSet[, columnCombinationsMatrix[,j]], trainingDataSet$Attrition, laplace = 1)
      iterationResultsDataframe[nrow(iterationResultsDataframe) + 1,] = c(confusionMatrix(table(predict(model, turnoverDataframe[, columnCombinationsMatrix[,j]]), turnoverDataframe$Attrition))$overall[1], confusionMatrix(table(predict(model, turnoverDataframe[, columnCombinationsMatrix[,j]]), turnoverDataframe$Attrition))$byClass[2], paste(columnCombinationsMatrix[,j], collapse = " "))
    }
    # Pass the mean accuracy/specificity from the iterationResultsDataframe into resultsDataframe
    resultsDataframe[nrow(resultsDataframe) + 1,] = c(mean(as.numeric(iterationResultsDataframe$accuracy)), mean(as.numeric(iterationResultsDataframe$specificity)), paste(columnCombinationsMatrix[,j], collapse = " "))
  }
  fileLocation = paste("C:/SMU MS Data Science/DoingDataScience6306/EmployeeAttrition/NaiveBayesResults/Combinations1/Results", i, ".csv", sep="")
  write.csv(resultsDataframe, fileLocation, row.names = TRUE)
}

resultsDataframe
```

```{r}
model = naiveBayes(trainingDataSet[, columnCombinationsMatrix[,j]], trainingDataSet$Attrition, laplace = 1)
confusionMatrix(table(predict(model, turnoverDataframe[, columnCombinationsMatrix[,j]]), turnoverDataframe$Attrition))
```

```{r}
confusionMatrix(table(predict(model, turnoverDataframe[, c(3, 5, 6)]), turnoverDataframe$Attrition))$overall[1]
confusionMatrix(table(predict(model, turnoverDataframe[, c(3, 5, 6)]), turnoverDataframe$Attrition))$byClass[2]
```

```{r}
trainingPercent = numberOfYesObservations / numberOfNoObservations

#Seperate the yes/no attrition observations into 2 dataframes
noAttritionTrainingDataframe = turnoverDataframe[turnoverDataframe$Attrition == 'No',]
yesAttritionTrainingDataframe = turnoverDataframe[turnoverDataframe$Attrition == 'Yes',]

iterations = 25

columnCombinations = c(3,4,5,6,7,8,9,10,11,13,14,15,16,17,18,19,20,21,22,23,24,25,26)

iterationResultsDataframe = data.frame(accuracy = double(), specificity = double(), combination = character())
for(l in 1:iterations){
  # TODO: figure out how to test on the full dataset instead of the trainingDataSet
  # https://stackoverflow.com/questions/66004740/how-to-apply-knn-model-on-the-test-dataset-after-cross-validation-in-r
  
  trainingIndicies = sample(1:dim(noAttritionTrainingDataframe)[1], round(trainingPercent * dim(noAttritionTrainingDataframe)[1]))
  trainingDataSet = rbind(noAttritionTrainingDataframe[trainingIndicies,], yesAttritionTrainingDataframe)
  
  model = naiveBayes(trainingDataSet[, c(3, 5, 6)], trainingDataSet$Attrition, laplace = 1)
  iterationResultsDataframe[nrow(iterationResultsDataframe) + 1,] = c(confusionMatrix(table(predict(model, trainingDataSet[, c(3, 5, 6)]), trainingDataSet$Attrition))$overall[1], confusionMatrix(table(predict(model, trainingDataSet[, c(3, 5, 6)]), trainingDataSet$Attrition))$byClass[2], paste(c(3, 5, 6), collapse = " "))
}
# Pass the mean accuracy/specificity from the iterationResultsDataframe into resultsDataframe
resultsDataframe[nrow(resultsDataframe) + 1,] = c(mean(as.numeric(iterationResultsDataframe$accuracy)), mean(as.numeric(iterationResultsDataframe$specificity)), paste(columnCombinationsMatrix[,j], collapse = " "))

resultsDataframe
```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```
