---
title: "ModelAnalysis"
author: "Derek Rogers"
date: "2022-11-30"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(ggplot2)
library(plyr)

knnResults2 = data.frame(read.csv("C:/SMU MS Data Science/DoingDataScience6306/EmployeeAttrition/KnnResults/Combinations2/Results2.csv"))
knnResults3 = data.frame(read.csv("C:/SMU MS Data Science/DoingDataScience6306/EmployeeAttrition/KnnResults/Combinations2/Results3.csv"))
knnResults4 = data.frame(read.csv("C:/SMU MS Data Science/DoingDataScience6306/EmployeeAttrition/KnnResults/Combinations2/Results4.csv"))
knnResults5 = data.frame(read.csv("C:/SMU MS Data Science/DoingDataScience6306/EmployeeAttrition/KnnResults/Combinations2/Results5.csv"))
```

```{r}
naiveBayesResults2 = data.frame(read.csv("C:/SMU MS Data Science/DoingDataScience6306/EmployeeAttrition/NaiveBayesResults/Combinations1/Results2.csv"))
naiveBayesResults3 = data.frame(read.csv("C:/SMU MS Data Science/DoingDataScience6306/EmployeeAttrition/NaiveBayesResults/Combinations1/Results3.csv"))
naiveBayesResults4 = data.frame(read.csv("C:/SMU MS Data Science/DoingDataScience6306/EmployeeAttrition/NaiveBayesResults/Combinations1/Results4.csv"))
```

```{r}
# 9 - JobInvolvement
# 18 - StockOptionLevel
```

```{r}
knnResults2$meanAccuracySpecificity = (knnResults2$accuracy + knnResults2$specificity) / 2
knnResults2$knnCombinationSize = 2

knnResults3$meanAccuracySpecificity = (knnResults3$accuracy + knnResults3$specificity) / 2
knnResults3$knnCombinationSize = 3

knnResults4$meanAccuracySpecificity = (knnResults4$accuracy + knnResults4$specificity) / 2
knnResults4$knnCombinationSize = 4

knnResults5$meanAccuracySpecificity = (knnResults5$accuracy + knnResults5$specificity) / 2
knnResults5$knnCombinationSize = 5

#Print out best mean accuracy for all Knn results
knnResults2 = knnResults2[order(-knnResults2$meanAccuracySpecificity),]
knnResults3 = knnResults3[order(-knnResults3$meanAccuracySpecificity),]
knnResults4 = knnResults4[order(-knnResults4$meanAccuracySpecificity),]
knnResults5 = knnResults5[order(-knnResults5$meanAccuracySpecificity),]
```

```{r}
naiveBayesResults2$meanAccuracySpecificity = (naiveBayesResults2$accuracy + naiveBayesResults2$specificity) / 2
naiveBayesResults2$knnCombinationSize = 2

naiveBayesResults3$meanAccuracySpecificity = (naiveBayesResults3$accuracy + naiveBayesResults3$specificity) / 2
naiveBayesResults3$knnCombinationSize = 3

naiveBayesResults4$meanAccuracySpecificity = (naiveBayesResults4$accuracy + naiveBayesResults4$specificity) / 2
naiveBayesResults4$knnCombinationSize = 4

naiveBayesResults2 = naiveBayesResults2[order(-naiveBayesResults2$meanAccuracySpecificity),]
naiveBayesResults3 = naiveBayesResults3[order(-naiveBayesResults3$meanAccuracySpecificity),]
naiveBayesResults4 = naiveBayesResults4[order(-naiveBayesResults4$meanAccuracySpecificity),]
```

```{r}
knnResults2
knnResults3
knnResults4
knnResults5

naiveBayesResults2
naiveBayesResults3
naiveBayesResults4
```

```{r}
#Append the top 25 best performing combinations for combinations of 2 through 5
top25KnnCombinations = knnResults2[1:25, 5]
top25KnnCombinations = append(top25Combinations, knnResults3[1:25, 5])
top25KnnCombinations = append(top25Combinations, knnResults4[1:25, 5])
top25KnnCombinations = append(top25Combinations, knnResults5[1:25, 5])
```

```{r}
variableFrequencyVectorKnn = c()
for(i in 1:length(top25KnnCombinations)){
  variableFrequencyVectorKnn = append(variableFrequencyVectorKnn, str_split(top25KnnCombinations[i], " ")[[1]])
}

KnnResultsDataframe = as.data.frame(table(variableFrequencyVectorKnn))
KnnResultsDataframe$variableNames = mapvalues(KnnResultsDataframe$variableFrequencyVectorKnn,
                                              from = c("6","7","9","10","11","14","16","17","18","20","21","23","24","25","26"),
                                              to = c("Education","Env Satisfaction","Job Involvement","Job Level","Job Satisfaction","Num Comp Worked","Performance Rating","Relat Satisfaction","Stock Option", "Training Times","Work Life Balance", "Years Cur Role", "Years Last Promo", "Years W/ Curr Manager", "Log(Monthly Income)"))

KnnResultsDataframe

ggplot(KnnResultsDataframe, aes(x=reorder(variableNames, -Freq), y = Freq)) + 
    geom_bar(stat="identity") +
    theme(axis.text.x = element_text(size = rel(2), angle = 90, vjust = .5)) +
    labs(title="Frequency of variables in top performing knn models", 
      y="Frequency", 
      x="Variable Name")
```

```{r}
#Append the top 25 best performing combinations for combinations of 2 through 5
top25NaiveBayesCombinations = c()
top25NaiveBayesCombinations = naiveBayesResults2[1:25, 4]
top25NaiveBayesCombinations = append(top25Combinations, naiveBayesResults3[1:25, 4])
top25NaiveBayesCombinations = append(top25Combinations, naiveBayesResults4[1:25, 4])
```

```{r}
variableFrequencyVectorNaiveBayes = c()
for(i in 1:length(top25NaiveBayesCombinations)){
  variableFrequencyVectorNaiveBayes = append(variableFrequencyVectorNaiveBayes, str_split(top25NaiveBayesCombinations[i], " ")[[1]])
}
NaiveBayesResultsDataframe = as.data.frame(table(variableFrequencyVectorNaiveBayes))

# 6, 7, 9, 10, 11, 14, 16, 17, 18, 20, 21, 23, 24, 25, 26
NaiveBayesResultsDataframe$variableNames = mapvalues(NaiveBayesResultsDataframe$variableFrequencyVectorNaiveBayes,
                                              from = c("6","7","9","10","11","14","16","17","18","20","21","23","24","25","26"),
                                              to = c("Education","Env Satisfaction","Job Involvement","Job Level","Job Satisfaction","Num Comp Worked","Performance Rating","Relat Satisfaction","Stock Option", "Training Times","Work Life Balance", "Years Cur Role", "Years Last Promo", "Years W/ Curr Manager", "Log(Monthly Income)"))

NaiveBayesResultsDataframe

ggplot(NaiveBayesResultsDataframe, aes(x=reorder(variableNames, -Freq), y = Freq)) + 
    geom_bar(stat="identity") +
    theme(axis.text.x = element_text(size = rel(2), angle = 90, vjust = .5)) +
    labs(title="Frequency of variables in top performing naive bayes models", 
       y="Frequency", 
       x="Variable Name")
```

```{r}

```

```{r}

```